/**
 * METRA — pages/reports/ReportsPage.tsx
 * Route: /app/reports
 * Lists all generated test reports & finalized evaluation certificates.
 * Backed by FastAPI backend with laboratory isolation.
 */

import { useEffect, useState } from "react";
import { useNavigate } from "react-router-dom";
import { HugeiconsIcon } from "@hugeicons/react";
import {
  FileTextIcon,
  Download01Icon,
  ViewIcon,
} from "@hugeicons/core-free-icons";

import { AppLayout } from "@/components/layout/AppLayout";
import { PageHeader } from "@/components/common/PageHeader";
import { StatusBadge, ResultBadge } from "@/components/common/StatusBadge";
import { EmptyState, LoadingState } from "@/components/common/EmptyState";
import { Button } from "@/components/ui/button";
import { listReports, type ReportListItem } from "@/services/api/reports";

export default function ReportsPage() {
  const navigate = useNavigate();
  const [reports, setReports] = useState<ReportListItem[]>([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    document.title = "METRA — Test Reports";
    listReports()
      .then(setReports)
      .catch((err) => console.error("Failed to load reports:", err))
      .finally(() => setLoading(false));
  }, []);

  const formatDate = (dateStr: string) => {
    if (!dateStr) return "—";
    return new Date(dateStr).toLocaleDateString("en-IN", {
      day: "2-digit",
      month: "short",
      year: "numeric",
    });
  };

  return (
    <AppLayout>
      <PageHeader
        title="Test Reports & Certificates"
        description="Official OIML R-76 Type Evaluation certificates and test reports"
      />

      <div className="rounded-lg border border-border bg-card shadow-sm">
        {loading ? (
          <LoadingState message="Loading laboratory reports..." />
        ) : reports.length === 0 ? (
          <EmptyState
            icon={FileTextIcon}
            title="No reports available"
            description="Reports are automatically generated when evaluations are completed and finalized."
            action={
              <Button size="sm" onClick={() => navigate("/app/evaluations")}>
                View Evaluations
              </Button>
            }
          />
        ) : (
          <div className="overflow-x-auto">
            <table className="w-full text-sm" role="table">
              <thead>
                <tr className="border-b border-border bg-muted/30">
                  <th className="px-4 py-3 text-left text-xs font-medium text-muted-foreground uppercase tracking-wide">
                    Report ID
                  </th>
                  <th className="px-4 py-3 text-left text-xs font-medium text-muted-foreground uppercase tracking-wide">
                    Instrument Model
                  </th>
                  <th className="px-4 py-3 text-left text-xs font-medium text-muted-foreground uppercase tracking-wide">
                    Serial No
                  </th>
                  <th className="px-4 py-3 text-left text-xs font-medium text-muted-foreground uppercase tracking-wide">
                    Generated By
                  </th>
                  <th className="px-4 py-3 text-left text-xs font-medium text-muted-foreground uppercase tracking-wide">
                    Date
                  </th>
                  <th className="px-4 py-3 text-left text-xs font-medium text-muted-foreground uppercase tracking-wide">
                    Result
                  </th>
                  <th className="px-4 py-3 text-right text-xs font-medium text-muted-foreground uppercase tracking-wide">
                    Actions
                  </th>
                </tr>
              </thead>
              <tbody className="divide-y divide-border">
                {reports.map((rpt) => (
                  <tr key={rpt.id} className="hover:bg-accent/50 transition-colors">
                    <td className="px-4 py-3 font-mono text-xs font-medium text-foreground">
                      {rpt.id}
                    </td>
                    <td className="px-4 py-3 font-medium text-foreground text-xs">
                      {rpt.instrument_manufacturer} {rpt.instrument_model}
                    </td>
                    <td className="px-4 py-3 font-mono text-xs text-muted-foreground">
                      {rpt.serial_number}
                    </td>
                    <td className="px-4 py-3 text-xs text-foreground">
                      {rpt.generated_by}
                    </td>
                    <td className="px-4 py-3 text-xs text-muted-foreground">
                      {formatDate(rpt.generated_at)}
                    </td>
                    <td className="px-4 py-3">
                      <ResultBadge result={(rpt.overall_result as any) || "PASS"} size="sm" />
                    </td>
                    <td className="px-4 py-3 text-right">
                      <Button
                        variant="ghost"
                        size="sm"
                        onClick={() => navigate(`/app/reports/${rpt.id}`)}
                        className="text-xs gap-1"
                      >
                        <HugeiconsIcon icon={ViewIcon} strokeWidth={2} className="size-3.5" />
                        Preview Report
                      </Button>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        )}
      </div>
    </AppLayout>
  );
}
