/**
 * METRA — pages/reports/ReportsPage.tsx
 * Route: /app/reports
 * Lists all generated test reports & finalized evaluation certificates.
 * Backed by FastAPI backend with laboratory isolation.
 */

import { useEffect, useState } from "react";
import { useNavigate } from "react-router-dom";
import { HugeiconsIcon } from "@hugeicons/react";
import {
  FileTextIcon,
  ViewIcon,
  CheckmarkCircle02Icon,
  Cancel01Icon,
} from "@hugeicons/core-free-icons";
import { toast } from "sonner";

import { AppLayout } from "@/components/layout/AppLayout";
import { PageHeader } from "@/components/common/PageHeader";
import { StatusBadge } from "@/components/common/StatusBadge";
import { EmptyState, LoadingState } from "@/components/common/EmptyState";
import { Button } from "@/components/ui/button";
import { useAuth } from "@/hooks/use-auth";
import {
  listReports,
  approveReport,
  rejectReport,
  type ReportListItem,
} from "@/services/api/reports";

export default function ReportsPage() {
  const navigate = useNavigate();
  const { profile } = useAuth();
  const [reports, setReports] = useState<ReportListItem[]>([]);
  const [loading, setLoading] = useState(true);
  const [actionLoading, setActionLoading] = useState<string | null>(null);

  // Rejection modal state
  const [rejectTarget, setRejectTarget] = useState<ReportListItem | null>(null);
  const [rejectReason, setRejectReason] = useState("");

  const loadData = () => {
    listReports()
      .then(setReports)
      .catch((err) => {
        console.error("Failed to load reports:", err);
        toast.error("Failed to load reports");
      })
      .finally(() => setLoading(false));
  };

  useEffect(() => {
    document.title = "METRA — Test Reports";
    loadData();
  }, []);

  const formatDate = (dateStr: string) => {
    if (!dateStr) return "—";
    return new Date(dateStr).toLocaleDateString("en-IN", {
      day: "2-digit",
      month: "short",
      year: "numeric",
    });
  };

  const isOwnerOrAdmin = profile?.role === "owner" || profile?.role === "admin";

  const handleApprove = async (rpt: ReportListItem) => {
    try {
      setActionLoading(rpt.evaluation_id);
      await approveReport(rpt.evaluation_id);
      toast.success(`Evaluation ${rpt.id} approved successfully`);
      loadData();
    } catch (err: any) {
      toast.error(err.message || "Failed to approve evaluation");
    } finally {
      setActionLoading(null);
    }
  };

  const handleConfirmReject = async () => {
    if (!rejectTarget || !rejectReason.trim()) return;
    try {
      setActionLoading(rejectTarget.evaluation_id);
      await rejectReport(rejectTarget.evaluation_id, rejectReason.trim());
      toast.success(`Evaluation ${rejectTarget.id} rejected for rework`);
      setRejectTarget(null);
      setRejectReason("");
      loadData();
    } catch (err: any) {
      toast.error(err.message || "Failed to reject evaluation");
    } finally {
      setActionLoading(null);
    }
  };

  return (
    <AppLayout>
      <PageHeader
        title="Test Reports & Certificates"
        description="Official OIML R-76 Type Evaluation certificates and test reports"
      />

      <div className="rounded-lg border border-border bg-card shadow-sm">
        {loading ? (
          <LoadingState message="Loading laboratory reports..." />
        ) : reports.length === 0 ? (
          <EmptyState
            icon={FileTextIcon}
            title="No reports available"
            description="Reports are automatically generated when evaluations are completed and submitted for verification."
            action={
              <Button size="sm" onClick={() => navigate("/app/evaluations")}>
                View Evaluations
              </Button>
            }
          />
        ) : (
          <div className="overflow-x-auto">
            <table className="w-full text-sm" role="table">
              <thead>
                <tr className="border-b border-border bg-muted/70">
                  <th className="w-[12%] px-4 py-3 text-left text-xs font-medium text-foreground uppercase tracking-wide">
                    Report ID
                  </th>
                  <th className="w-[22%] px-4 py-3 text-left text-xs font-medium text-foreground uppercase tracking-wide">
                    Instrument Model
                  </th>
                  <th className="w-[15%] px-4 py-3 text-left text-xs font-medium text-foreground uppercase tracking-wide">
                    Serial No
                  </th>
                  <th className="w-[17%] px-4 py-3 text-left text-xs font-medium text-foreground uppercase tracking-wide">
                    Generated By
                  </th>
                  <th className="w-[12%] px-4 py-3 text-left text-xs font-medium text-foreground uppercase tracking-wide">
                    Date
                  </th>
                  <th className="w-[12%] px-4 py-3 text-left text-xs font-medium text-foreground uppercase tracking-wide">
                    Status
                  </th>
                  <th className="w-[10%] px-4 py-3 text-right text-xs font-medium text-foreground uppercase tracking-wide">
                    Actions
                  </th>
                </tr>
              </thead>
              <tbody className="divide-y divide-border">
                {reports.map((rpt) => {
                  const statusUpper = String(rpt.evaluation_status || rpt.status || "").toUpperCase();
                  const isPending = statusUpper === "PENDING_VERIFICATION";
                  const isBusy = actionLoading === rpt.evaluation_id;

                  return (
                    <tr key={rpt.id} className="hover:bg-accent/50 transition-colors">
                      <td className="w-[12%] px-4 py-3 font-mono text-xs font-medium text-foreground whitespace-nowrap">
                        {rpt.id}
                      </td>
                      <td className="w-[22%] px-4 py-3 font-medium text-foreground text-xs">
                        {rpt.instrument_manufacturer} {rpt.instrument_model}
                      </td>
                      <td className="w-[15%] px-4 py-3 font-mono text-xs text-muted-foreground whitespace-nowrap">
                        {rpt.serial_number}
                      </td>
                      <td className="w-[17%] px-4 py-3 text-xs text-foreground font-medium whitespace-nowrap">
                        {rpt.generated_by}
                      </td>
                      <td className="w-[12%] px-4 py-3 text-xs text-muted-foreground whitespace-nowrap">
                        {formatDate(rpt.generated_at)}
                      </td>
                      <td className="w-[12%] px-4 py-3 whitespace-nowrap">
                        <StatusBadge
                          type="evaluation"
                          status={rpt.evaluation_status || rpt.status}
                          size="sm"
                        />
                      </td>
                      <td className="w-[10%] px-4 py-3 text-right whitespace-nowrap">
                        <div className="flex items-center justify-end gap-1.5">
                          <Button
                            variant="ghost"
                            size="sm"
                            onClick={() => navigate(`/app/reports/${rpt.evaluation_id}`)}
                            className="text-xs gap-1"
                          >
                            <HugeiconsIcon icon={ViewIcon} strokeWidth={2} className="size-3.5" />
                            Preview Report
                          </Button>

                          {isOwnerOrAdmin && isPending && (
                            <>
                              <Button
                                variant="outline"
                                size="sm"
                                disabled={isBusy}
                                onClick={() => handleApprove(rpt)}
                                className="text-xs gap-1 border-emerald-500/30 text-emerald-700 hover:bg-emerald-500/10 dark:text-emerald-400"
                              >
                                <HugeiconsIcon icon={CheckmarkCircle02Icon} strokeWidth={2} className="size-3.5" />
                                Approve
                              </Button>
                              <Button
                                variant="outline"
                                size="sm"
                                disabled={isBusy}
                                onClick={() => {
                                  setRejectTarget(rpt);
                                  setRejectReason("");
                                }}
                                className="text-xs gap-1 border-rose-500/30 text-rose-700 hover:bg-rose-500/10 dark:text-rose-400"
                              >
                                <HugeiconsIcon icon={Cancel01Icon} strokeWidth={2} className="size-3.5" />
                                Reject
                              </Button>
                            </>
                          )}
                        </div>
                      </td>
                    </tr>
                  );
                })}
              </tbody>
            </table>
          </div>
        )}
      </div>

      {/* Rejection Modal */}
      {rejectTarget && (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/50 p-4">
          <div className="w-full max-w-md rounded-lg border border-border bg-card p-6 shadow-lg">
            <h3 className="text-base font-semibold text-foreground mb-1">Reject Evaluation for Rework</h3>
            <p className="text-xs text-muted-foreground mb-4">
              Please provide a clear reason for rejecting report <strong>{rejectTarget.id}</strong> back to the testing engineer.
            </p>
            <textarea
              value={rejectReason}
              onChange={(e) => setRejectReason(e.target.value)}
              placeholder="Enter rejection reason / required corrections..."
              className="w-full rounded-md border border-input bg-background p-2.5 text-xs text-foreground focus:outline-none focus:ring-2 focus:ring-primary mb-4"
              rows={4}
            />
            <div className="flex justify-end gap-2">
              <Button
                variant="outline"
                size="sm"
                onClick={() => {
                  setRejectTarget(null);
                  setRejectReason("");
                }}
              >
                Cancel
              </Button>
              <Button
                variant="destructive"
                size="sm"
                disabled={!rejectReason.trim() || !!actionLoading}
                onClick={handleConfirmReject}
              >
                {actionLoading ? "Rejecting..." : "Confirm Rejection"}
              </Button>
            </div>
          </div>
        </div>
      )}
    </AppLayout>
  );
}
